import type {ExampleDefinition} from '@omap/example-kit';

export const exampleCatalog: ExampleDefinition[] = [
  {
    id: 'map-basic-osm',
    title: '基础地图与 OSM 底图',
    category: '地图基础',
    description: '创建地图、视图和基础瓦片图层。',
    tags: ['Map', 'View', 'OSM'],
    sourcePath: 'src/examples/BasicMap.vue',
    capabilities: ['map.lifecycle', 'layer.osm'],
  },
  {
    id: 'core-runtime',
    title: '事件、Scope 与 Registry',
    category: '地图基础',
    description: '演示类型安全事件、资源作用域和运行时注册中心。',
    tags: ['Events', 'Scope', 'Registry'],
    sourcePath: 'src/examples/CoreRuntime.vue',
    capabilities: ['core.events', 'core.scope', 'core.registry'],
  },
  {
    id: 'layer-management',
    title: '图层管理与底图切换',
    category: '图层核心',
    description: '按 ID 查找图层，切换底图，控制显隐、透明度与顺序。',
    tags: ['Layers', 'Basemap', 'Opacity', 'Order'],
    sourcePath: 'src/examples/LayerManagement.vue',
    capabilities: ['layer.collection', 'layer.basemap', 'layer.state'],
  },
  {
    id: 'layer-sources',
    title: '数据源状态与格式图层',
    category: '图层核心',
    description: '查看数据源状态与加载事件，刷新底图，并定位 WKT 图层范围。',
    tags: ['Sources', 'Loading', 'WKT', 'Fit'],
    sourcePath: 'src/examples/LayerSources.vue',
    capabilities: ['layer.source', 'layer.loading', 'layer.wkt', 'map.fit'],
  },
  {
    id: 'control-management',
    title: '控件管理与标准控件',
    category: '控件核心',
    description: '按 ID 管理原生控件，切换启用状态、位置和集合顺序。',
    tags: ['Controls', 'ScaleLine', 'MousePosition', 'FullScreen'],
    sourcePath: 'src/examples/ControlManagement.vue',
    capabilities: ['control.collection', 'control.state', 'control.factories'],
  },
  {
    id: 'interaction-management',
    title: '交互管理与绘制编辑',
    category: '交互核心',
    description: '通过互斥组切换选择、绘制、修改和平移，并保持捕捉交互并行运行。',
    tags: ['Interactions', 'Draw', 'Modify', 'Translate', 'Snap'],
    sourcePath: 'src/examples/InteractionManagement.vue',
    capabilities: ['interaction.collection', 'interaction.exclusive', 'interaction.factories'],
  },
  {
    id: 'planned-ogc',
    title: 'OGC 服务接入（规划）',
    category: '地图服务',
    description: 'WMS、WMTS、WFS、OGC API Features/Tiles 与 STAC。',
    tags: ['OGC', 'WMS', 'WMTS', 'WFS'],
    sourcePath: 'src/examples/PlannedExample.vue',
    capabilities: ['service.ogc'],
  },
];
